### PR TITLE
fix FUSEQE-10939 - Added missing integrations

### PR DESCRIPTION
**Pull request by lfabriko**
- Previously I forgot to add URI and secret based configuration groovy files
- Edited keys in property file
- Completed Readme

### CODE REVIEW

**Review by christophd — APPROVED** [review]
Good, thanks!

I wonder though wether the test variants for uri based and secret based should go into separate feature files. When all is mixed into one feature that might be more difficult to follow for first-time readers. WDYT?

**Review by oscerd — APPROVED** [review]

**Comment by lfabriko** [comment]
@christophd I am not sure what is best solution; my idea was that as all three integrations do the same in principle and vary only in configuration, it would be easy to understand that once some action is triggered, they all listen to it and receive correctly the same message/object.

**Comment by christophd** [comment]
@lfabriko If one of the configuration options has a problem the whole feature fails. I can imagine that it will be more straightforward to find out which of the options was causing the error when each option is in a separate feature.

How about using a [Scenario Outline](https://cucumber.io/docs/gherkin/reference/#scenario-outline)? In the table of examples we can add all configuration options as variants and each given option is then run as a separate Scenario while keeping it all in one single feature.

**Comment by lfabriko** [comment]
The Scenario Outline sounds great, as it would avoid overhead with creating new object/sending message for each configuration separately.

**Comment by christophd** [comment]
merging this PR as we can add Scenario Outline in a separate PR

**Pull request merged**
