### PR TITLE
ENTESB-17616 Update non-working examples in Kamelet Catalog docs

### PR DESCRIPTION
**Pull request by claudio4j**
* There are some generated kamelet bindings are invalid, the auto
  generation cannot resolve all the required steps, so there is
  a need to create it manually
* Add a comment marker in kamelet binding examples for the auto
  generation to skip its creation
* The doc generation source the kamelet binding example file when it
  doesn't auto generate the example

### CODE REVIEW

**Comment by claudio4j** [comment]
@oscerd @squakez I would like your review before I push the final bits.

**Comment by claudio4j** [comment]
Only the `avro-deserialize-action` and `avro-serialize-action` kamelet binding examples are provided for review, but once we are good, I am going to fix all the other examples.

**Review by oscerd — APPROVED** [review]

**Comment by oscerd** [comment]
LGTM, but we need to do upstream first

**Review by squakez — CHANGES_REQUESTED** [review]
We should provide the changes upstream first. Then, the `kamelet-catalog-1.7` branch is not yet ready to accept any change as it is used for testing CPAAS pipeline only. Anything for 1.7 (or whichever is next minor) should be on hold, or, promoted for 1.6.6 (next patch version).

**Comment by claudio4j** [comment]
the generator in camel-kamelets upstream is a javascript program and this repo is not forked from upstream, so it was my understanding this work could be done first here. Anyway I am happy to receive this feedback about the idea, which is good and I will add this to upstream. Thanks for the review.

**Comment by oscerd** [comment]
Yes, it's really divergent, but nevertheless it would be nice to have upstream too.

**Comment by claudio4j** [comment]
Closing this as 1.7 branch is not to be used. Going to open a PR for 1.6 branch.

**Pull request closed without merging**
