### PR TITLE
[ENTESB-15377] Add basic aws sqs test

### PR DESCRIPTION
**Pull request by tplevko**
The client can be placed to some other place, it's ATM in my repository - https://github.com/tplevko/aws-sqs-docker-image. @christophd - do you think the client could be moved to citrusframework org?

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by christophd** [comment]
@tplevko I can push the aws-sqs-client image to Dockerhub.io with the `yaks` user just like I did with the telegram-client: https://hub.docker.com/r/yaks/telegram-client

We could also have a look at the official AWS client Docker image (https://hub.docker.com/r/amazon/aws-cli). Maybe we can use this to send SQS messages, too?

**Comment by christophd** [comment]
... and we could use the YAKS steps and make use of the Camel AWS SQS component to send the SQS message. 

I am evaluating this for AWS Kinesis at the moment. It looks like this:

```
Given Camel exchange message header CamelAwsKinesisPartitionKey="123"
Given Camel exchange body: ${streamData}
When send Camel exchange to("aws-kinesis:${aws.kinesis.stream}?accessKey=${aws-kinesis.accessKey}&secretKey=${aws-kinesis.secretKey}&region=${aws-kinesis.region}")
```

This would replace the Docker image and use the Camel AWS component directly to send the message to AWS.

You need to add the `camel-aws-sqs` dependency in yaks-config.yaml then like I did with AWS Kinesis:

```yaml
config:
  runtime:
    resources:
      - aws-kinesis-source.kamelet.yaml
      - aws-kinesis-to-log.groovy
      - aws-kinesis-client.yaml
    settings:
      dependencies:
        - groupId: org.apache.camel
          artifactId: camel-aws-kinesis
          version: "@camel.version@"
```

Just an idea

**Review by christophd — APPROVED** [review]
I think this is a valid setup. As mentioned in the comments we could think of using the default AWS client Docker image or use the Camel AWS SQS component in the YAKS test to send the SQS message.

**Comment by christophd** [comment]
@tplevko FYI. The evaluation on AWS Kinesis went great! I am using the official AWS cli Docker image (https://hub.docker.com/r/amazon/aws-cli) for creating the Kinesis data stream. And I am using the Kinesis Camel component to actually send the message to the data stream.

**Comment by tplevko** [comment]
@christophd in that case I'll try also the AWS cli Docker image and rewrite this test, so it's more in sync with the rest of the tests and I won't have to extend and maintain the image I created.

**Comment by christophd** [comment]
@tplevko you want to apply the changes to this PR or merge and open another PR? I am fine with merging now

**Comment by tplevko** [comment]
@christophd in case you are OK with the PR, then you can merge. I'll provide the updated test after the holidays

**Pull request merged**
