### PR TITLE
CMLK-1662 Update kamelet-catalog 2.2.x to Camel K 2.2.0

### PR DESCRIPTION
**Pull request by claudio4j**
based on upstream: https://github.com/apache/camel-kamelets/pull/1617

### CODE REVIEW

**Comment by claudio4j** [comment]
for review: @christophd @squakez

**Review by oscerd — APPROVED** [review]

**Comment by oscerd** [comment]
Maybe it makes sense to start from a tag from camel-kamelets upstream? Also aren't we going to target Camel 4.4.0 for the next Camel K?

**Comment by claudio4j** [comment]
> Maybe it makes sense to start from a tag from camel-kamelets upstream? 

I am planning to have a jboss-fuse/camel-kamelets fork from apache/camel-kamelets, to facilitate future sync as we have for the other upstream/downstream projects.
For this moment I thought to approximate this PR to the upstream camel-kamelets/4.0.3 to facilitate the fork in the near time and to have the QE tests started.

> Also aren't we going to target Camel 4.4.0 for the next Camel K?

This can be easily changed later taking in consideration the release from camel-quarkus.

**Review by squakez — DISMISSED** [review]
I am sorry, but downstream we're not going to productize all those Kamelets. Please, mind that we only must to include the Kamelets which will belong to the list of productized ones.

In the future we need to rethink more in general the distribution model, but for the time being we probably stick to the distribution model we used to have for v1.

**Comment by claudio4j** [comment]
> include the Kamelets which will belong to the list of productized ones.

I am going to look at the list of supported kamelets. The intention of this commit is to include all the kamelets and to have a camel k 2.2.0 build with these kamelets , then subsequently I will provide another change removing the unsupported kamelets.

**Comment by claudio4j** [comment]
I am working to remove all the kamelets marked as community and planned and will amend this PR.

**Review by squakez — COMMENTED** [review]
The way the productization works, requires the kamelets to be available in the root directory, not under `/kamelets` as it happens upstream. Also, it seems we're bringing in documentation and other stuff that probably won't be required downstream either. IMO, we should just sync the existing downstream kamelets with the new definition. At a later stage we may review how we're distributing the Kamelets and have a better way to sync them between upstream and downstream.

**Comment by claudio4j** [comment]
Only the kamelets marked as "supported" are present, the docs were regenerated.

**Comment by claudio4j** [comment]
Can this be merged ?

**Comment by claudio4j** [comment]
Do you think there is any pending work in this PR ?

**Comment by claudio4j** [comment]
There were some changes in the supported kamelets documentation. I updated the kamelets, tests, docs and templates. Let me know if there is any concern with this update.

**Comment by oscerd** [comment]
Looking again at this, I believe it is too big. In my opinion we need to cherry-pick only the new Kamelets and leave the structure as-is. We are already divergent in comparison with the upstream, so it's not a matter of being aligned. It's much more important to have control on the needed bits and eventually we can rework the structure later.

**Review by oscerd — CHANGES_REQUESTED** [review]
I commented again, to me this needs to be closed and reworked

**Comment by claudio4j** [comment]
I will provide a summary of the main changes:
* Upgrade of the camel-k from 1.10 to 2.2
* Upgrade of the camel-k crd api from v1alpha1 to v1
* Relocation of kamelets files from root directory to kamelets directory
* A new maven module `library/camel-kamelets` derived from `library/camel-kamelets-catalog`
* Alignment of the camel core version to 4.0.3 used both in camel k, camel-k-runtime and camel-quarkus
* Added the data types work introduced in camel 4.0.3
* Added / removed kamelets accordingly to the [camel components documentation](https://docs.google.com/spreadsheets/d/1aNgEDmpSM9tMEOzBZjiLeQkKWNNN_t_d1b2KwKD0IS4/edit#gid=1650668658)
* The number of kamelets were *reduced* from 86 to 70

Unfortunately there are a large number of files touched by this change, but if you look the actual changes, they are mostly about moving files.

If the camel version is different from 4.0.3, the productization in PNC will package an additional camel version in the mrrc zip file (and their transitive dependencies), leading to validation failures.

**Comment by oscerd** [comment]
I don't think the PNC validation failure is a good reason to completely change the structure of this repository. It's already a mess to keep track of changes and backporting, this way it will be even harder.

**Comment by claudio4j** [comment]
If the main concern is the location of the kamelet.yaml files, they can go back to the root directory, this would be no problem. But related to the other changes, do you think they can be skipped ?

**Comment by oscerd** [comment]
It depends: 

Upgrade of the camel-k from 1.10 to 2.2 -> I suppose this is needed
Upgrade of the camel-k crd api from v1alpha1 to v1 -> This one too
Relocation of kamelets files from root directory to kamelets directory -> I don't think this one is needed, at least not in that folder
A new maven module library/camel-kamelets derived from library/camel-kamelets-catalog -> I don't think everything is useful from library
Alignment of the camel core version to 4.0.3 used both in camel k, camel-k-runtime and camel-quarkus -> if we are going to use 4.4.0 as productization target, I don't see why this needed now.
Added the data types work introduced in camel 4.0.3 -> this is needed, but much of the work is in 4.4.0
Added / removed kamelets accordingly to the [camel components documentation] (https://docs.google.com/spreadsheets/d/1aNgEDmpSM9tMEOzBZjiLeQkKWNNN_t_d1b2KwKD0IS4/edit#gid=1650668658) -> this is needed, but just a subset of kamelets are really required

**Comment by claudio4j** [comment]
As agreed, the kamelets were relocated back to the root directory and there is no `library/camel-kamelets` maven module.

**Comment by claudio4j** [comment]
@oscerd @squakez is there any pending requests to merge this one ?

**Comment by squakez** [comment]
> @oscerd @squakez is there any pending requests to merge this one ?

Not from my side. As I've mentioned already in a few occasions, if QE is happy with the change, no objection from me.

**Review by oscerd — APPROVED** [review]

**Pull request merged**
