### PR TITLE
Update to template, but Kafka

### PR DESCRIPTION
**Pull request by squakez**

### CODE REVIEW

**Comment by christophd** [comment]
@squakez this run has been successful 🤔

**Comment by squakez** [comment]
> @squakez this run has been successful thinking

It's strange, as the first attempt had the same failures we have in #223 . Re-trying again to see what happens. Were there finally any change needed in Yaks to align the `.template` usage? In that case we can focus on that change, rebase #223 and see if that fixes.

**Comment by christophd** [comment]
the YAKS changes regarding `template` vs. `flow` should be merged with this PR: #227

feel free to rebase #223 and try but I think it is another issue

still trying to find out what is going on my PR with files dump enabled https://github.com/christophd/kamelet-catalog/pull/5

**Comment by squakez** [comment]
The new attempt worked as well, so, definitely the problem appears to be related to the usage of `.spec.template`.

**Pull request closed without merging**
