### PR TITLE
Aws kinesis source

### PR DESCRIPTION
**Pull request by oscerd**

### CODE REVIEW

**Comment by lfabriko** [comment]
I am sorry, I proactively tried the fix, but still got issues (with same setup as described in ENTESB-16432):
```
1] 2021-06-23 08:36:51,292 INFO  [io.quarkus] (main) Installed features: [camel-attachments, camel-aws2-commons, camel-aws2-kinesis, camel-bean, camel-core, camel-k-cloudevents, camel-k-core, camel-k-knative, camel-k-knative-producer, camel-k-runtime, camel-kamelet, camel-platform-http, camel-support-common, camel-support-commons-logging, camel-yaml-dsl, cdi, mutiny, smallrye-context-propagation, vertx, vertx-web]
[1] 2021-06-23 08:37:07,962 ERROR [org.apa.cam.pro.err.DefaultErrorHandler] (Camel (camel-1) thread #0 - aws2-kinesis://kamelet-sample) Failed delivery for (MessageId: B3E6A05CF7DC513-0000000000000000 on ExchangeId: B3E6A05CF7DC513-0000000000000000). Exhausted after delivery attempt: 1 caught: org.apache.camel.language.bean.RuntimeBeanExpressionException: Failed to invoke method: asUtf8String on null due to: java.io.UncheckedIOException: Cannot encode string.
[1] 
[1] Message History (complete message history is disabled)
[1] ---------------------------------------------------------------------------------------------------------------------------------------
[1] RouteId              ProcessorId          Processor                                                                        Elapsed (ms)
[1] [source            ] [source            ] [from[aws2-kinesis://kamelet-sample?accessKey=RAW(xxx)&region=] [        75]
[1]     ...
[1] [source            ] [setBody1          ] [setBody[simple{${body.data.asUtf8String}}]                                    ] [         0]
[1] 
[1] Stacktrace
[1] ---------------------------------------------------------------------------------------------------------------------------------------
[1] : org.apache.camel.language.bean.RuntimeBeanExpressionException: Failed to invoke method: asUtf8String on null due to: java.io.UncheckedIOException: Cannot encode string.
[1]     at org.apache.camel.language.bean.BeanExpression.invokeOgnlMethod(BeanExpression.java:453)
[1]     at org.apache.camel.language.bean.BeanExpression.evaluate(BeanExpression.java:199)
[1]     at org.apache.camel.language.bean.BeanExpression.evaluate(BeanExpression.java:214)
[1]     at org.apache.camel.language.simple.SimpleExpressionBuilder$28.evaluate(SimpleExpressionBuilder.java:757)
[1]     at org.apache.camel.support.ExpressionAdapter.evaluate(ExpressionAdapter.java:45)
[1]     at org.apache.camel.processor.SetBodyProcessor.process(SetBodyProcessor.java:45)
[1]     at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$SimpleTask.run(RedeliveryErrorHandler
```

**Comment by oscerd** [comment]
The error is different

**Comment by oscerd** [comment]
It looks like there is no data in the record.

**Comment by lfabriko** [comment]
This was output of running integration, prior to sending data...

**Comment by oscerd** [comment]
I cannot reproduce this with 1.5.0 snapshot. Btw I'll try. It is eventually a different issue like dealing with an empty body probably

**Comment by oscerd** [comment]
This is with 1.4.0 and without any data in the Kinesis Stream

```
[1] 2021-06-23 09:47:24,808 INFO  [org.apa.cam.k.Runtime] (main) Apache Camel K Runtime 1.7.0
[1] 2021-06-23 09:47:25,022 INFO  [org.apa.cam.qua.cor.CamelBootstrapRecorder] (main) bootstrap runtime: org.apache.camel.quarkus.main.CamelMainRuntime
[1] 2021-06-23 09:47:25,439 INFO  [org.apa.cam.k.lis.SourcesConfigurer] (main) Loading routes from: SourceDefinition{name='aws-kinesis-source', language='yaml', type='template', propertyNames='[accessKey, region, secretKey, stream]', location='file:/etc/camel/sources/aws-kinesis-source.yaml', }
[1] 2021-06-23 09:47:25,578 INFO  [org.apa.cam.k.lis.SourcesConfigurer] (main) Loading routes from: SourceDefinition{name='log-sink', language='yaml', type='template', location='file:/etc/camel/sources/log-sink.yaml', }
[1] 2021-06-23 09:47:25,579 INFO  [org.apa.cam.k.lis.SourcesConfigurer] (main) Loading routes from: SourceDefinition{name='camel-k-embedded-flow', language='yaml', location='file:/etc/camel/sources/camel-k-embedded-flow.yaml', }
[1] 2021-06-23 09:47:26,236 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Routes startup summary (total:3 started:3)
[1] 2021-06-23 09:47:26,236 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main)     Started route1 (kamelet://aws-kinesis-source/source)
[1] 2021-06-23 09:47:26,236 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main)     Started source (aws2-kinesis://streamTest)
[1] 2021-06-23 09:47:26,236 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main)     Started sink (kamelet://source)
[1] 2021-06-23 09:47:26,237 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Apache Camel 3.9.0 (camel-1) started in 434ms (build:0ms init:72ms start:362ms)
[1] 2021-06-23 09:47:26,239 INFO  [io.quarkus] (main) camel-k-integration 1.4.0 on JVM (powered by Quarkus 1.13.0.Final) started in 2.361s. 
[1] 2021-06-23 09:47:26,240 INFO  [io.quarkus] (main) Profile prod activated. 
[1] 2021-06-23 09:47:26,240 INFO  [io.quarkus] (main) Installed features: [camel-aws2-commons, camel-aws2-kinesis, camel-bean, camel-core, camel-k-core, camel-k-loader-yaml, camel-k-runtime, camel-kamelet, camel-log, camel-support-common, camel-support-commons-logging, camel-yaml-dsl, cdi]
```

**Comment by oscerd** [comment]
I cannot reproduce what you're reporting.

**Pull request merged**
