### PR TITLE
CMLK-270 - camel-azure-servicebus support

### PR DESCRIPTION
**Pull request by oscerd**

### CODE REVIEW

**Review by squakez — APPROVED** [review]
LGTM, thanks! BTW, what do you use to regen documentation? I think we need to include it in the init/sync process.

**Comment by oscerd** [comment]
The go generator from here: https://github.com/openshift-integration/kamelet-catalog/blob/release-2.0.x/script/generator/README.md

**Comment by oscerd** [comment]
Let's merge this and we can automate it somewhat.

**Comment by squakez** [comment]
> The go generator from here: https://github.com/openshift-integration/kamelet-catalog/blob/release-2.0.x/script/generator/README.md

That is enough for me to include it in the automated process, thanks!

**Pull request merged**
