### PR TITLE
Move kamelet version updates to groovy to standardize with productization

### PR DESCRIPTION
**Pull request by cunningt**

### CODE REVIEW

**Comment by cunningt** [comment]
We need to be able to run the update kamelets step within productization before tagging occurs.    The easiest option seems to be to translate the ant replacement over to groovy, and that way any additional patterns that we decide to add replacements for will be picked up both in community releases and in productization.

**Review by nicolaferraro — APPROVED** [review]
Looks great @cunningt !
Just one thing, would it work if we move the script to `script/version` (there's already a `script` dir with other utils) instead of `src/main/script`. I'd like to sync this with upstream and a `src` dir in the root may be confising.

**Review by oscerd — APPROVED** [review]

**Comment by cunningt** [comment]
@nicolaferraro Can we cherry-pick this over to kamelet-catalog-1.4 branch too?

**Comment by nicolaferraro** [comment]
> @nicolaferraro Can we cherry-pick this over to kamelet-catalog-1.4 branch too?

Sure, will do a batch sync of the 1.4 branch

**Pull request merged**
